pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'devsecops-usach-laboratorio-final'
    projectKey: 'devsecops-usach-laboratorio-final'
    projectName: 'spring-boot-kubernetes'
    
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'adolfohernandeztapia'

